### ISSUE TITLE
В коде нигде не используются указатели на структуры

### ISSUE THREAD

**Issue by Shidlowski** [PavloKirif/exercise_1.1#2]
https://github.com/PavloKirif/exercise_1.1/blob/88887a13782cfa015558183a8a6febe3a75eccb3/main.cpp#L7
Объявить указатель типа структуры (объект структуры) и выделить память для хранения данных одной структуры.
Данное правило нигде не выполняется. Вектор содержит объекты структуры, но никак не указатели на них.
Если есть вектор, то почему в него не добавляются новые элементы?

**Comment by PavloKirif** [comment]
Исправлено
