### ISSUE TITLE
Убрать библиотеку из одной структуры

### ISSUE THREAD

**Issue by Shidlowski** [PavloKirif/exercise_1.1#3]
https://github.com/PavloKirif/exercise_1.1/blob/88887a13782cfa015558183a8a6febe3a75eccb3/struct_data/data.cpp#L4
Лучше вынести структуру просто в основной код, либо просто подключить. В данном случае через Cmake создается либа, а там ты ее подключаешь. Пока нам это не нужно

**Comment by PavloKirif** [comment]
Исправлено
